spring.application.name=fashion-store-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fashion_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-secret-key-to-a-long-random-production-secret
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://10.36.212.5:5173
